# We use AppVeyor to build our Windows binaries automatically:
#
# https://ci.appveyor.com/project/nathan_dunfield/cypari

environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    #- PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python34-x64"
    #- PYTHON: "C:\\Python35"
    #- PYTHON: "C:\\Python36"

install:
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  
  # Install python packages
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools"
  - "%PYTHON%\\python.exe -m pip install Cython six wheel future"

  # Set up the 32-bit MinGW compilers
  - set PATH=C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%;
  - set MSYSTEM=MINGW32
  - cd Version2\Windows\toolchain
  - "bash install_files_32.sh"
  - cd ..\..

  #- Set up the 64-bit MinGW compilers
  #- set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;
  #- set MSYSTEM=MINGW64
  #- cd Version2\Windows\toolchain
  #- "bash install_files_64.sh"
  #- cd ..\..

  # Build CyPari. 
  - "%PYTHON%\\python.exe setup.py build -c mingw32"

build:
  none

test_script:
  # Put your test command here.
  - cd build\\lib.win32-2.7
  - "%PYTHON%\\python.exe -m cypari.test"
  
after_test:
  # This step builds your wheels.
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: Version2\dist\*.whl

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
