/* Generated by Cython 0.24 */

#ifndef __PYX_HAVE__cypari__cysignals__signals
#define __PYX_HAVE__cypari__cysignals__signals


#ifndef __PYX_HAVE_API__cypari__cysignals__signals

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) sig_raise_exception(int, char const *);

#endif /* !__PYX_HAVE_API__cypari__cysignals__signals */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsignals(void);
#else
PyMODINIT_FUNC PyInit_signals(void);
#endif

#endif /* !__PYX_HAVE__cypari__cysignals__signals */
