# We use AppVeyor to build our Windows binaries automatically:
#
# https://ci.appveyor.com/project/culler/cypari-mac

branches:
  only:
    - current_pari

image: macOS

matrix:
  -
    stack: python 3.8

  -
    stack: python 3.7
  
install:

  # Show our build system
  - sh: echo ${APPVEYOR_BUILD_WORKER_IMAGE}
  - sh: python3 --version
  - sh: pwd
  - sh: ls

  # Install python packages
  - sh: python3 -m pip install cython

  # Build CyPari. 
  - sh: ls
  - sh: python3 setup.py build

cache:
  - /Users/appveyor/libcache

build:
  none

test_script:
  - sh: python3 setup.py test
  
after_test:
  - sh: python3 setup.py bdist_wheel

artifacts:
  - path: dist/*.whl

# on_success:
#   You can use this step to upload your artifacts to a public website.
#   See Appveyor's documentation for more details. Or you can simply
#   access your wheels from the Appveyor "artifacts" tab for your build.
