# https://ci.appveyor.com/project/culler/cypari-mac

image: macOS

branches:
  only:
    - master

init:
  # Currently the cache fails because 7-Zip is missing
  # FIX ME when the new image is released.
  - sh: brew install p7zip

environment:
  matrix:
    - VENV: /Users/appveyor/venv2.7.17
    - VENV: /Users/appveyor/venv3.8.2
    - VENV: /Users/appveyor/venv3.7.5
    - VENV: /Users/appveyor/venv3.6.10
    - VENV: /Users/appveyor/venv3.5.9

install:

  # Print some environment info
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: pwd
  - sh: ls /Users/appveyor

  # Activate a virtualenv
  - sh: source $VENV/bin/activate

  # Install required python packages
  - python -m pip install cython
  - sh: which cython || true
  - sh: python -c "import Cython" || true

  # Build CyPari.
  - sh: python setup.py build

build:
  none

test_script:
  - sh: python setup.py test
  
after_test:
  - sh: python setup.py bdist_wheel
  - sh: python macOS/rename_wheels.py

artifacts:
  - path: dist/*.whl

cache:
  - libcache -> macOS/clear_cache.txt

# on_success:
#   You can use this step to upload your artifacts to a public website.
#   See Appveyor's documentation for more details. Or you can simply
#   access your wheels from the Appveyor "artifacts" tab for your build.
