name: 64 bit Windows Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for 64 bit Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
  
    steps:       
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install a Python to use for building
        with:
          python-version: '3.11'
          
      - uses: msys2/setup-msys2@v2
        name: Setup an msys2 environment
        with:
          msystem: UCRT64
          release: false
          install: >-
            base-devel
            m4
            bison
            make
            patch
            sed
          pacboy: gcc:p
          path-type: inherit
          
      - name: Expand the path for Visual Studio 2019
        run: |
          echo "/c/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64" >> $GITHUB_PATH

      - name: Install python packages for building (needs msys2)
        run: |
          python -m pip install wheel
          python -m pip install cibuildwheel
          python -m pip install cython
          
      - name: Build gmp and pari
        run: |
          bash build_pari.sh pari64 gmp64

      - name: Build many wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: AMD64
          CIBW_SKIP: cp27-* cp35-* pp*
          CIBW_BEFORE_BUILD: |
            pip install cython
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v3
        name: Save the wheels as artifacts
        with:
          path: ./wheelhouse/*.whl
