name: Linux Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: |
          python3.10 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3.10 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp39-manylinux_x86-64 cp310-manylinux_x86_64 cp311-manylinux_x86-64 cp312-manylinux_x86_64
          CIBW_BEFORE_BUILD: |            
            python -m pip install Cython>=3.0.0
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --strip -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
