name: Linux Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    env:
      SHELL: /usr/bin/bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7, 3.5, 32 bit Linux, and PyPy
          CIBW_SKIP: cp27-* cp35-* *-manylinux_i686 *musllinux* pp*
          CIBW_BEFORE_BUILD: |            
            pip install cython
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --strip -w {dest_dir} {wheel}
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
