name: macOS Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Skip Python 2.7, 3.5, and PyPy
          CIBW_SKIP: cp27-* cp35-* pp*
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_BEFORE_BUILD: |        
            pip install cython
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
