name: macOS Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.12'
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp38* cp39* cp310* cp311* cp312*
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_BEFORE_BUILD: |
            pip install cython>=3.0.0
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
