name: macOS Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: 3.12
      - name: Install cibuildwheel
        run: |
 	  python3 -m pip install Cython>=3.0.0
          python3 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp312-* cp311-* cp310-* cp39-* 
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_BEFORE_BUILD: |
            python -m pip install Cython>=3.0.0
          CIBW_TEST_COMMAND: python -m cypari.test

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
